name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Pilves
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Snake'
